import { Box, Divider, Stack, StackDivider, Text, SimpleGrid, useColorModeValue as mode } from "@chakra-ui/react"
import * as React from "react"
import { FaMobileAlt, FaShieldAlt } from "react-icons/fa"
import { Description } from "./Description"
import { FullWidthContainer } from "../../blocks/full-width-container"
import { Heading } from "../../typography/heading"

export const FeatureDetails = () => (
  <FullWidthContainer as="section" bg={mode(`gray.100`, `inherit`)} py="100">
    <Box textAlign="center" py="10">
      <Heading as="h2">How GatsbyJs faciliate to Business Owners</Heading>
    </Box>
    <SimpleGrid columns={2} spacing={10} mb="3.5rem">
      <Box maxW={{ base: `xl`, md: `7xl` }} mx="auto">
        <Box rounded={{ lg: `lg` }} bg={mode(`white`, `gray.700`)} maxW="3xl" mx="auto" shadow="base" overflow="hidden">
          <Box px="6" py="4">
            <Text as="h3" fontWeight="bold" fontSize="lg">
              Built for high performance
            </Text>
            <Text color={mode(`gray.600`, `gray.300`)} fontSize="sm">
              Working with Gatsby Agency or developers allows you to follow the latest web standards and technologies
              like ReactJS, Webpack, GraphQL, modern ES6+ JavaScript and CSS.
            </Text>
          </Box>
          <Divider />
          <Stack spacing="6" divider={<StackDivider />} py="5" px="8">
            <Description isRecommended title="Multiple data sources" icon={<FaShieldAlt />}>
              You can use any number of different data files locally. You can also pull data from remote sources such as
              WordPress, Medium, etc. Anything accessible with API.
            </Description>
            <Description title="Scalability you can count on" icon={<FaMobileAlt />}>
              The price for the hosting of Gatsby websites starts from $0!
            </Description>
            <Description title="HEADLESS ECOMMERCE PLATFORMS" icon={<FaMobileAlt />}>
              Receive a prompt from your mobile app to confirm it’s you.
            </Description>
          </Stack>
        </Box>
      </Box>
      <Box maxW={{ base: `xl`, md: `7xl` }} mx="auto">
        <Box rounded={{ lg: `lg` }} bg={mode(`white`, `gray.700`)} maxW="3xl" mx="auto" shadow="base" overflow="hidden">
          <Box px="6" py="4">
            <Text as="h3" fontWeight="bold" fontSize="lg">
              Built for Best of the best SEO
            </Text>
            <Text color={mode(`gray.600`, `gray.300`)} fontSize="sm">
              Working with Gatsby Agency or developers allows you to follow the latest web standards and technologies
              like ReactJS, Webpack, GraphQL, modern ES6+ JavaScript and CSS.
            </Text>
          </Box>
          <Divider />
          <Stack spacing="6" divider={<StackDivider />} py="5" px="8">
            <Description isRecommended title="PERFORMANT MARKETING PAGES" icon={<FaShieldAlt />}>
              Enter a code generated by your authenticator app to confirm it’s you.
            </Description>
            <Description title="SUPER-FAST DIGITAL BUSINESS PAGE" icon={<FaMobileAlt />}>
              Receive a prompt from your mobile app to confirm it’s you.
            </Description>
            <Description title="HEADLESS ECOMMERCE PLATFORMS" icon={<FaMobileAlt />}>
              Receive a prompt from your mobile app to confirm it’s you.
            </Description>
          </Stack>
        </Box>
      </Box>
    </SimpleGrid>
  </FullWidthContainer>
)
